version: 2
updates:
  - package-ecosystem: gradle
    directory: "/exoquery-sample-codegen"
    schedule:
      interval: weekly
    rebase-strategy: auto
    open-pull-requests-limit: 5
    groups:
      kotlin-and-exoquery:
        patterns:
          - "org.jetbrains.kotlin:*"          # Kotlin stdlib, reflect, gradle plugin, including kotlin-serialization plugin
          - "org.jetbrains.kotlinx:kotlinx-serialization-*"  # kotlinx serialization libraries
          - "io.exoquery:*"
  - package-ecosystem: gradle
    directory: "/exoquery-sample-codegen-ai"
    schedule:
      interval: weekly
    rebase-strategy: auto
    open-pull-requests-limit: 5
    groups:
      kotlin-and-exoquery:
        patterns:
          - "org.jetbrains.kotlin:*"          # Kotlin stdlib, reflect, gradle plugin, including kotlin-serialization plugin
          - "org.jetbrains.kotlinx:kotlinx-serialization-*"  # kotlinx serialization libraries
          - "io.exoquery:*"
  - package-ecosystem: gradle
    directory: "/exoquery-sample-codegen-ai-ollama"
    schedule:
      interval: weekly
    rebase-strategy: auto
    open-pull-requests-limit: 5
    groups:
      kotlin-and-exoquery:
        patterns:
          - "org.jetbrains.kotlin:*"          # Kotlin stdlib, reflect, gradle plugin, including kotlin-serialization plugin
          - "org.jetbrains.kotlinx:kotlinx-serialization-*"  # kotlinx serialization libraries
          - "io.exoquery:*"
